"Set ruler(bottom) and line number
set ruler

"Set line number
set number

"Enable synmtax
syntax on

"Loading tags
set tags=./tags,tags;$HOME

"set colorschme
colorscheme desert

"set highlight
se cursorline
highlight cursorline ctermbg=darkgray cterm=NONE

""""""""""""""""""""""""""""""
" Tag list (ctags)
""""""""""""""""""""""""""""""
let Tlist_Ctags_Cmd="/usr/local/bin/ctags"
let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1
let Tlist_Auto_Open=1

" Configuration file for vim
set modelines=0		" CVE-2007-2438

" size of a hard tabstop
set tabstop=4

" Normally we use vim-extensions. If you want true vi-compatibility
" remove change the following statements
set nocompatible	" Use Vim defaults instead of 100% vi compatibility
set backspace=2		" more powerful backspacing

" Don't write backup file if vim is being called by "crontab -e"
au BufWrite /private/tmp/crontab.* set nowritebackup
" Don't write backup file if vim is being called by "chpass"
au BufWrite /private/etc/pw.* set nowritebackup
